version: "3"
services:
  booked:
    build:
      context: .
      args:
        VERSION: 2.8.2
    image: mkdryden/docker-booked
    environment:
        BOOKED_APP_TITLE: "Booked Scheduler"
        BOOKED_DEFAULT_TIMEZONE: "America/Toronto"
        BOOKED_ALLOW_SELF_REGISTRATION: "true"
        BOOKED_ADMIN_EMAIL: "admin@example.com"
        BOOKED_WEB_URL: "http://localhost/Web"
        BOOKED_REGISTRATION_REQUIRE_EMAIL_ACTIVATION: "true"
        BOOKED_INSTALL_PASSWORD: ""
        BOOKED_EMAIL_DEFAULT_FROM_ADDRESS: "no-reply@example.com"
        BOOKED_EMAIL_DEFAULT_FROM_NAME: "Booked Scheduler"
        BOOKED_RESERVATION_ALLOW_WAIT_LIST: "true"
        BOOKED_SCHEDULE_USE_PER_USER_COLORS: "true"
        BOOKED_PRIVACY_VIEW_SCHEDULES: "true"
        BOOKED_PRIVACY_VIEW_RESERVATIONS: "true"
        BOOKED_PRIVACY_HIDE_USER_DETAILS: "true"
        BOOKED_RESERVATION_DESCRIPTION_REQUIRED: "true"
        BOOKED_PHPMAILER_MAILER: "smtp"
        BOOKED_PHPMAILER_SMTP_HOST: ""
        BOOKED_PHPMAILER_SMTP_SECURE: "tls"
        BOOKED_PHPMAILER_SMTP_USERNAME: ""
        BOOKED_PHPMAILER_SMTP_PASSWORD: ""
    volumes:
      - webroot:/var/www
    labels:
      deck-chores.reminders.command: php -f /var/www/booked/Jobs/sendreminders.php
      deck-chores.reminders.interval: every minute
      deck-chores.reminders.jitter: 10
      deck-chores.autorelease.command: php -f /var/www/booked/Jobs/autorelease.php
      deck-chores.autorelease.interval: every minute
      deck-chores.autorelease.jitter: 10
      deck-chores.missedcheckin.command: php -f /var/www/booked/Jobs/sendmissedcheckin.php
      deck-chores.missedcheckin.interval: every minute
      deck-chores.missedcheckin.jitter: 10
      deck-chores.waitlist.command: php -f /var/www/booked/Jobs/sendwaitlist.php
      deck-chores.waitlist.interval: every minute
      deck-chores.waitlist.jitter: 10
    depends_on:
      - mysql
      - officer

  mysql:
    image: mysql:8
    volumes:
      - sqldata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=bookedscheduler
      - MYSQL_USER=booked_user
      - MYSQL_PASSWORD=password
      - MYSQL_RANDOM_ROOT_PASSWORD=true

  web:
    image: nginx:latest
    ports:
      - 80
    volumes:
      - webroot:/var/www
      - ./site.conf:/etc/nginx/conf.d/default.conf

  officer:
    image: funkyfuture/deck-chores:1
    restart: unless-stopped
    environment:
      TIMEZONE: America/Toronto
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  sqldata:
  webroot: